package com.example.myapplication.src;

import java.security.MessageDigest;
import java.security.NoSuchAlgorithmException;
import java.util.ArrayList;
import java.util.List;
import java.util.UUID;


/**
 * This class manages user information.
 *
 * Responsibilities:
 * - Store user information such as username, email, password, contact info, etc.
 * - Manage the user's own posts, liked posts, and purchased posts.
 *
 * @author Yingxuan Tang, Yichi Zhang u7748799, Linxiang Hu u7633783, Wenhui Shi, Jin Yang
 */
public class User {
    private static int nextUserIndex = 4000;  // The initial value is set to 4000

    private String userId;  // UUID only used internally
    private String email;   // Username
    private String passwordHash;
    private String name;
    private String address;
    private String phone;
    private PostList postList;  // Add PostList attribute
    private String userType;    // "0": Admin, "1": Normal user
    private String userIndexInFirebase;
    private List<Post> ownPosts;
    private List<Post> likePosts;
    private List<Post> buyPosts;

    // Constructor with only email and password
    public User(String email, String password) {
        this.userId = UUID.randomUUID().toString(); // Generate a unique user ID using UUID
        this.email = email;
        this.passwordHash = password;
        this.userType = "1";
        this.userIndexInFirebase = generateNextUserIndex();  // Assign the next user index
        this.ownPosts = new ArrayList<>();
        this.likePosts = new ArrayList<>();
        this.buyPosts = new ArrayList<>();
    }

    // Constructor used for direct import from Firebase (userId is not autogenerated)
    public User(String userId, String email, String password, String name, String address, String phone, String userType, String userIndexInFirebase) {
        this.userId = userId;
        this.email = email;
        this.passwordHash = password;
        this.name = name;
        this.address = address;
        this.phone = phone;
        this.userType = userType;
        this.userIndexInFirebase = userIndexInFirebase;   // Assign the next user index
        this.ownPosts = new ArrayList<>();
        this.likePosts = new ArrayList<>();
        this.buyPosts = new ArrayList<>();
    }

    /**
     * Generates the next user index.
     *
     * @return The next user index.
     */
    public static synchronized String generateNextUserIndex() {
        return String.valueOf(nextUserIndex++);  // Increment and return the next index
    }

    /**
     * Hashes a password using SHA-256.
     *
     * @param password The password to hash.
     * @return The hashed password.
     */
    public static String hashPassword(String password) {
        try {
            MessageDigest digest = MessageDigest.getInstance("SHA-256");
            byte[] hash = digest.digest(password.getBytes());
            StringBuilder hexString = new StringBuilder();
            for (byte b : hash) {
                String hex = Integer.toHexString(0xff & b);
                if (hex.length() == 1) hexString.append('0');
                hexString.append(hex);
            }
            return hexString.toString();
        } catch (NoSuchAlgorithmException e) {
            throw new RuntimeException("Failed to hash password", e);
        }
    }

    // Update password
    public void updatePassword(String newPassword) {
        this.passwordHash = hashPassword(newPassword);
    }

    // Update name
    public void updateName(String newName) {
        this.name = newName;
    }

    // Update address
    public void updateAddress(String newAddress) {
        this.address = newAddress;
    }

    // Update phone number
    public void updatePhone(String newPhone) {
        this.phone = newPhone;
    }

    // Getters and Setters
    public String getUserId() {
        return userId;
    }

    public String getPasswordHash() {
        return passwordHash;
    }

    public String getName() {
        return name;
    }

    public String getEmail() {
        return email;
    }

    public String getAddress() {
        return address;
    }

    public String getPhone() {
        return phone;
    }

    public void setEmail(String email) {
        this.email = email;
    }

    public void setName(String name) {
        this.name = name;
    }


    // Add a post to the user's own posts
    public void addOwnPost(Post post) {
        if (post != null) {
            this.ownPosts.add(post);
        }
    }

    public void updateLikes(Post post){
        if(!likePosts.contains(post)) {
            this.likePosts.add(post);
        }
    }

    public void updateBuys(Post post){
        if(!buyPosts.contains(post)) {
            this.buyPosts.add(post);
        }
    }

    public void updateOwns(Post post){
        this.ownPosts.add(post);
    }

    // Get all posts owned by the user
    public List<Post> getOwnPosts() {
        return this.ownPosts;
    }

    // Get all posts liked by the user
    public List<Post> getLikePosts() {
        return this.likePosts;
    }

    // Get all posts purchased by the user
    public List<Post> getBuyPosts() {
        return this.buyPosts;
    }

    public String getUserIndexInFirebase() {
        return userIndexInFirebase;
    }

    public String getUserType() {
        return userType;
    }
}
